#%RAML 0.8
---
title: Calculator
version: v1
baseUri: http://127.0.0.1/{version}
/calculator:
  get:
    description: Entry for the calculator resource
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "operations": ["add", "subtract", "divide"]
                "href_self": "http://127.0.0.1/v1/calculator"
              }
  /{command}:
    get:
      queryParameters:
        numbers:
          description: a list of numbers to add
          example: 1
          required: true
          type: integer
      description: Runs specified command
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "Results" : 3
                }
